service: todolist-backend-dymanoDB

plugins:
  # - "@hewmen/serverless-plugin-typescript"
  # - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-plugin-scripts

custom:
  # Enable warmup on all functions (only for production and staging)
  warmup:
    - production
    - staging
  scripts:
    hooks:
      deploy:createDeploymentArtifacts: yarn run build
  TodosTable:
    name: TodosTable-${self:provider.stage}
    arn: !GetAtt TodosTable.Arn

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  profile: toanle
  environment:
    TODO_TABLE_NAME: ${self:custom.TodosTable.name}
    SLS_DEBUG: '*'
  iamRoleStatements:
    - ${file(iam/TodosTableIAM.yml):TodosTableIAM}

resources:
  Resources:
    TodosTable: ${file(resources/TodosTable.yml):TodosTable}

functions:
  handler:
    handler: ./.build/lambda.handler
    memorySize: 256
    timeout: 10
    events:
      - http:
          method: any
          path: /{any+}
