service: todolist-dymanodb

plugins:
  - serverless-offline
  - serverless-plugin-scripts
  - serverless-dotenv-plugin

custom:
  # Enable warmup on all functions (only for production and staging)
  scripts:
    hooks:
      deploy:createDeploymentArtifacts: yarn run build
  TodosTable:
    name: TodosTable-${self:provider.stage}
    arn: !GetAtt TodosTable.Arn

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region:  ${env:REGION, 'ap-southeast-1'}
  profile: ${env:PROFILE, 'toanle'}
  environment:
    TODO_TABLE_NAME: ${self:custom.TodosTable.name}
    ACCESSKEYID: ${env:ACCESSKEYID}
    SECRETACCESSKEY: ${env:SECRETACCESSKEY}
    COGNITO_REGION: ${env:COGNITO_REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    SLS_DEBUG: "*"
  iamRoleStatements:
    - ${file(iam/TodosTableIAM.yml):TodosTableIAM}

resources:
  Resources:
    TodosTable: ${file(resources/TodosTable.yml):TodosTable}

functions:
  handler:
    handler: ./.build/lambda.handler
    memorySize: 256
    timeout: 10
    events:
      - http:
          method: any
          path: /{any+}
